#!/usr/bin/env bash
# ==============================================================================
# agy_bootstrapper Installer Script (GitHub Copilot CLI Edition)
# ==============================================================================
set -e

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASHRC_PATH="$HOME/.bashrc"

echo "==============================================="
echo " Installing Copilot Partner Bootstrapper"
echo " Target Directory: $INSTALL_DIR"
echo "==============================================="

# Parse arguments
yolo_mode=""
for arg in "$@"; do
  case $arg in
    --yolo)
      yolo_mode="y"
      ;;
    --no-yolo)
      yolo_mode="n"
      ;;
    *)
      echo "Unknown option: $arg"
      echo "Usage: $0 [--yolo | --no-yolo]"
      exit 1
      ;;
  esac
done

# Interactive fallback
if [ -z "$yolo_mode" ]; then
  echo -n "Do you want to enable YOLO mode (skip permissions) by default? [y/N]: "
  read -r response
  if [[ "$response" =~ ^[yY]([eE][sS])?$ ]]; then
    yolo_mode="y"
  else
    yolo_mode="n"
  fi
fi

# Prepare YOLO flags
YOLO_FLAG=""
if [ "$yolo_mode" = "y" ]; then
  YOLO_FLAG=" --yolo"
  echo ">> YOLO mode enabled (permission prompts will be skipped)."
else
  echo ">> Standard mode enabled (permission prompts will be shown)."
fi

# Remove old block if exists
if [ -f "$BASHRC_PATH" ]; then
  echo ">> Cleaning old configurations in $BASHRC_PATH..."
  # Use temporary file to safely clean block
  TEMP_BASHRC=$(mktemp)
  sed '/# === AGY BOOTSTRAPPER (COPILOT) START ===/,/# === AGY BOOTSTRAPPER (COPILOT) END ===/d' "$BASHRC_PATH" > "$TEMP_BASHRC"
  cat "$TEMP_BASHRC" > "$BASHRC_PATH"
  rm -f "$TEMP_BASHRC"
fi

# Append new shortcuts block to .bashrc
echo ">> Appending new bootstrapper aliases to $BASHRC_PATH..."
cat << EOF >> "$BASHRC_PATH"

# === AGY BOOTSTRAPPER (COPILOT) START ===
# Partner Bootstrapper Shortcuts for GitHub Copilot CLI (Auto-generated by installer)
alias copsample='python3 $INSTALL_DIR/scripts/run_partner_copilot.py --persona sample --role programmer$YOLO_FLAG'
alias copsamplec='python3 $INSTALL_DIR/scripts/run_partner_copilot.py --persona sample --role programmer -c$YOLO_FLAG'
alias copreset='python3 $INSTALL_DIR/scripts/run_partner_copilot.py --reset$YOLO_FLAG'
copp() {
  python3 $INSTALL_DIR/scripts/run_partner_copilot.py --persona "\${1:-sample}" --role "\${2:-programmer}" "\${@:3}"$YOLO_FLAG
}
# === AGY BOOTSTRAPPER (COPILOT) END ===
EOF

echo "==============================================="
echo " Installation Complete!"
echo " Please run: source ~/.bashrc"
echo " Commands:"
echo "   copsample   - Start a fresh partner session (Copilot CLI)"
echo "   copsamplec  - Resume last partner session (Copilot CLI)"
echo "   copreset  - Reset to default agent mode (Copilot CLI)"
echo "   copp      - Run custom configuration (Copilot CLI)"
echo "==============================================="
