#!/usr/bin/env bash
# ==============================================================================
# agy_bootstrapper Unified Installer Script (agy / copilot / claude)
# ==============================================================================
set -e

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNNER="$INSTALL_DIR/scripts/run_partner.py"

# Target the rc file for the user's actual login shell, not always bash
# (zsh does not source ~/.bashrc, so aliases would silently never load).
case "$SHELL" in
  */zsh) RC_PATH="$HOME/.zshrc" ;;
  *) RC_PATH="$HOME/.bashrc" ;;
esac

echo "==============================================="
echo " Installing AI Partner Bootstrapper (Unified)"
echo " Target Directory: $INSTALL_DIR"
echo "==============================================="

# Parse arguments
yolo_mode=""
engines=""
profiles_repo=""
for arg in "$@"; do
  case $arg in
    --yolo)
      yolo_mode="y"
      ;;
    --no-yolo)
      yolo_mode="n"
      ;;
    --engine=*)
      engines="${arg#--engine=}"
      ;;
    --profiles-repo=*)
      profiles_repo="${arg#--profiles-repo=}"
      ;;
    *)
      echo "Unknown option: $arg"
      echo "Usage: $0 [--yolo | --no-yolo] [--engine=agy,copilot,claude|all] [--profiles-repo=owner/repo]"
      exit 1
      ;;
  esac
done

# Interactive fallback for engines
if [ -z "$engines" ]; then
  echo -n "Which engines do you want to install? (comma-separated: agy,copilot,claude or 'all') [agy]: "
  read -r engines
  engines="${engines:-agy}"
fi
if [ "$engines" = "all" ]; then
  engines="agy,copilot,claude"
fi

# Validate engines
for e in ${engines//,/ }; do
  case $e in
    agy|copilot|claude) ;;
    *)
      echo "Error: unknown engine '$e' (valid: agy, copilot, claude)"
      exit 1
      ;;
  esac
done

# Interactive fallback for YOLO
if [ -z "$yolo_mode" ]; then
  echo -n "Do you want to enable YOLO mode (skip permissions) by default? [y/N]: "
  read -r response
  if [[ "$response" =~ ^[yY]([eE][sS])?$ ]]; then
    yolo_mode="y"
  else
    yolo_mode="n"
  fi
fi

# Prepare YOLO flags
YOLO_FLAG=""
if [ "$yolo_mode" = "y" ]; then
  YOLO_FLAG=" --yolo"
  echo ">> YOLO mode enabled (confirm dialogs will be skipped)."
else
  echo ">> Standard mode enabled (permission prompts will be shown)."
fi

# Optional: clone a private "profiles" repo and symlink its personas/roles
# into place. See README.md "Private Profiles" for the expected layout.
# Once linked, run_partner.py auto-detects and syncs these paths on every run
# (git pull before, commit+push after) -- no further config needed here.
if [ -n "$profiles_repo" ]; then
  PROFILES_DIR="$INSTALL_DIR/.profiles"
  echo ">> Setting up private profiles from $profiles_repo..."
  if ! command -v gh >/dev/null 2>&1; then
    echo "  Warning: gh (GitHub CLI) not found; skipping private profiles setup."
  elif [ -d "$PROFILES_DIR/.git" ]; then
    echo "  Profiles already cloned: $PROFILES_DIR"
  elif ! gh repo clone "$profiles_repo" "$PROFILES_DIR"; then
    echo "  Warning: failed to clone $profiles_repo; skipping private profiles setup."
  fi

  if [ -d "$PROFILES_DIR" ]; then
    for d in "$PROFILES_DIR"/personas/*/; do
      [ -d "$d" ] || continue
      d="${d%/}"
      name="$(basename "$d")"
      if [ -d "$INSTALL_DIR/personas/$name" ] && [ ! -L "$INSTALL_DIR/personas/$name" ]; then
        rm -rf "$INSTALL_DIR/personas/$name"
      fi
      ln -sfn "$d" "$INSTALL_DIR/personas/$name"
      echo "  Linked persona: $name"
    done
    for d in "$PROFILES_DIR"/roles/*/; do
      [ -d "$d" ] || continue
      d="${d%/}"
      name="$(basename "$d")"
      if [ -d "$INSTALL_DIR/roles/$name" ] && [ ! -L "$INSTALL_DIR/roles/$name" ]; then
        rm -rf "$INSTALL_DIR/roles/$name"
      fi
      ln -sfn "$d" "$INSTALL_DIR/roles/$name"
      echo "  Linked role: $name"
    done
  fi
fi

# Remove old blocks if they exist (including legacy copilot block)
if [ -f "$RC_PATH" ]; then
  echo ">> Cleaning old configurations in $RC_PATH..."
  TEMP_RC=$(mktemp)
  sed -e '/# === AGY BOOTSTRAPPER START ===/,/# === AGY BOOTSTRAPPER END ===/d' \
      -e '/# === AGY BOOTSTRAPPER (COPILOT) START ===/,/# === AGY BOOTSTRAPPER (COPILOT) END ===/d' \
      "$RC_PATH" > "$TEMP_RC"
  cat "$TEMP_RC" > "$RC_PATH"
  rm -f "$TEMP_RC"
fi

# Alias prefix per engine: agy -> agy*, copilot -> cop*, claude -> cld*
prefix_for() {
  case $1 in
    agy) echo "agy" ;;
    copilot) echo "cop" ;;
    claude) echo "cld" ;;
  esac
}

# Append new shortcuts block to the rc file
echo ">> Appending new bootstrapper aliases to $RC_PATH..."
{
  echo ""
  echo "# === AGY BOOTSTRAPPER START ==="
  echo "# Partner Bootstrapper Shortcuts (Auto-generated by installer)"
  for e in ${engines//,/ }; do
    p="$(prefix_for "$e")"
    echo "alias ${p}sample='python3 $RUNNER --engine $e --persona sample --role programmer$YOLO_FLAG'"
    echo "alias ${p}samplec='python3 $RUNNER --engine $e --persona sample --role programmer -c$YOLO_FLAG'"
    echo "alias ${p}kaze='python3 $RUNNER --engine $e --persona yukikaze_future --role programmer$YOLO_FLAG'"
    echo "alias ${p}kazec='python3 $RUNNER --engine $e --persona yukikaze_future --role programmer -c$YOLO_FLAG'"
    echo "alias ${p}reset='python3 $RUNNER --engine $e --reset$YOLO_FLAG'"
    echo "${p}p() {"
    echo "  python3 $RUNNER --engine $e --persona \"\${1:-yukikaze_future}\" --role \"\${2:-programmer}\" \"\${@:3}\"$YOLO_FLAG"
    echo "}"
  done
  echo "# === AGY BOOTSTRAPPER END ==="
} >> "$RC_PATH"

echo "==============================================="
echo " Installation Complete!"
echo " Please run: source $RC_PATH"
echo " Installed engines: $engines"
if [ -n "$profiles_repo" ]; then
  echo " Private profiles: $profiles_repo"
fi
echo " Commands (per engine prefix: agy / cop / cld):"
echo "   <prefix>sample   - Start a fresh partner session"
echo "   <prefix>samplec  - Resume last partner session"
echo "   <prefix>reset    - Reset to default agent mode"
echo "   <prefix>p        - Run custom configuration"
echo "==============================================="
