#!/usr/bin/env bash
# ==============================================================================
# agy_bootstrapper Unified Installer Script (agy / copilot / claude)
# ==============================================================================
set -e

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BASHRC_PATH="$HOME/.bashrc"
RUNNER="$INSTALL_DIR/scripts/run_partner.py"

echo "==============================================="
echo " Installing AI Partner Bootstrapper (Unified)"
echo " Target Directory: $INSTALL_DIR"
echo "==============================================="

# Parse arguments
yolo_mode=""
engines=""
for arg in "$@"; do
  case $arg in
    --yolo)
      yolo_mode="y"
      ;;
    --no-yolo)
      yolo_mode="n"
      ;;
    --engine=*)
      engines="${arg#--engine=}"
      ;;
    *)
      echo "Unknown option: $arg"
      echo "Usage: $0 [--yolo | --no-yolo] [--engine=agy,copilot,claude|all]"
      exit 1
      ;;
  esac
done

# Interactive fallback for engines
if [ -z "$engines" ]; then
  echo -n "Which engines do you want to install? (comma-separated: agy,copilot,claude or 'all') [agy]: "
  read -r engines
  engines="${engines:-agy}"
fi
if [ "$engines" = "all" ]; then
  engines="agy,copilot,claude"
fi

# Validate engines
for e in ${engines//,/ }; do
  case $e in
    agy|copilot|claude) ;;
    *)
      echo "Error: unknown engine '$e' (valid: agy, copilot, claude)"
      exit 1
      ;;
  esac
done

# Interactive fallback for YOLO
if [ -z "$yolo_mode" ]; then
  echo -n "Do you want to enable YOLO mode (skip permissions) by default? [y/N]: "
  read -r response
  if [[ "$response" =~ ^[yY]([eE][sS])?$ ]]; then
    yolo_mode="y"
  else
    yolo_mode="n"
  fi
fi

# Prepare YOLO flags
YOLO_FLAG=""
if [ "$yolo_mode" = "y" ]; then
  YOLO_FLAG=" --yolo"
  echo ">> YOLO mode enabled (confirm dialogs will be skipped)."
else
  echo ">> Standard mode enabled (permission prompts will be shown)."
fi

# Remove old blocks if they exist (including legacy copilot block)
if [ -f "$BASHRC_PATH" ]; then
  echo ">> Cleaning old configurations in $BASHRC_PATH..."
  TEMP_BASHRC=$(mktemp)
  sed -e '/# === AGY BOOTSTRAPPER START ===/,/# === AGY BOOTSTRAPPER END ===/d' \
      -e '/# === AGY BOOTSTRAPPER (COPILOT) START ===/,/# === AGY BOOTSTRAPPER (COPILOT) END ===/d' \
      "$BASHRC_PATH" > "$TEMP_BASHRC"
  cat "$TEMP_BASHRC" > "$BASHRC_PATH"
  rm -f "$TEMP_BASHRC"
fi

# Alias prefix per engine: agy -> agy*, copilot -> cop*, claude -> cld*
prefix_for() {
  case $1 in
    agy) echo "agy" ;;
    copilot) echo "cop" ;;
    claude) echo "cld" ;;
  esac
}

# Append new shortcuts block to .bashrc
echo ">> Appending new bootstrapper aliases to $BASHRC_PATH..."
{
  echo ""
  echo "# === AGY BOOTSTRAPPER START ==="
  echo "# Partner Bootstrapper Shortcuts (Auto-generated by installer)"
  for e in ${engines//,/ }; do
    p="$(prefix_for "$e")"
    echo "alias ${p}sample='python3 $RUNNER --engine $e --persona sample --role programmer$YOLO_FLAG'"
    echo "alias ${p}samplec='python3 $RUNNER --engine $e --persona sample --role programmer -c$YOLO_FLAG'"
    echo "alias ${p}reset='python3 $RUNNER --engine $e --reset$YOLO_FLAG'"
    echo "${p}p() {"
    echo "  python3 $RUNNER --engine $e --persona \"\${1:-sample}\" --role \"\${2:-programmer}\" \"\${@:3}\"$YOLO_FLAG"
    echo "}"
  done
  echo "# === AGY BOOTSTRAPPER END ==="
} >> "$BASHRC_PATH"

echo "==============================================="
echo " Installation Complete!"
echo " Please run: source ~/.bashrc"
echo " Installed engines: $engines"
echo " Commands (per engine prefix: agy / cop / cld):"
echo "   <prefix>sample   - Start a fresh partner session"
echo "   <prefix>samplec  - Resume last partner session"
echo "   <prefix>reset    - Reset to default agent mode"
echo "   <prefix>p        - Run custom configuration"
echo "==============================================="
